---
- name: gater facts about servers
  hosts: centos_servers
  tasks: 
    - name: show ansible_os_family
      debug:
        msg: "{{ ansible_os_family }}"

    - name: show mount points
      debug:
        msg: "{{ ansible_mounts }}"
      when: ansible_os_family == 'RedHat'
